#define LED_PIN GPIO_PIN_3
#define LED_PORT GPIOC

#define ADC_SNS1_CS_PIN GPIO_PIN_4
#define ADC_SNS1_CS_PORT GPIOC

#define ADC_SNS1_DRDY_PIN GPIO_PIN_5
#define ADC_SNS1_DRDY_PORT GPIOC

#define ADC_SNS1_SYNCRESET_PIN GPIO_PIN_12
#define ADC_SNS1_SYNCRESET_PORT GPIOC

#define HSS_SR_EN_PIN GPIO_PIN_2
#define HSS_SR_EN_PORT GPIOB

#define HSS_SR_OUT_CLK_PIN GPIO_PIN_8
#define HSS_SR_OUT_CLK_PORT GPIOC
