# CRAZY COLORS ----------------------------------------------------------------
RED=\033[0;31m
GREEN=\033[0;32m
ORANGE=\033[0;33m
BLUE=\033[0;34m
PURPLE=\033[0;35m
CYAN=\033[0;36m
LIGHTGRAY=\033[0;37m
DARKGRAY=\033[1;30m
YELLOW=\033[0;33m
NC=\033[0m # No Color
# -----------------------------------------------------------------------------

# generate paths
MAKEFILE_DIR = $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

# PROJECT CONFIGURATION -------------------------------------------------------
TEST ?= main

# COMMON TARGETS
# LSOM: stm32g473xx
# PSOM: stm32l431cbt
# FAT NUCLEO: stm32g474xx
# BAD NUCLEO: stm32l432kcu
PROJECT_TARGET ?= stm32g474xx

# SOURCE AND INCLUDE DIRECTORIES
PROJECT_C_INCLUDES = $(wildcard core/inc) $(wildcard ../driver/inc)
PROJECT_C_SOURCES = $(wildcard core/src/*.c) $(wildcard ../driver/src/*.c)
PROJECT_MAIN_DIR ?= core/src

# BUILD DIRECTORIES
PROJECT_BUILD_DIR = build
BUILD_MAKEFILE_DIR ?= ../Embedded-Sharepoint

MADEFILE ?= true
MADEFILE_DIR = ${MAKEFILE_DIR}
# -----------------------------------------------------------------------------


# remove main and add test folders if running test
ifneq ($(TEST), "main")
	PROJECT_C_SOURCES := $(filter-out $(PROJECT_MAIN_DIR)/main.c, $(PROJECT_C_SOURCES))
	PROJECT_C_SOURCES += $(wildcard test/src/${test}.c)

	PROJECT_C_INCLUDES += $(wildcard /test/inc)
endif

# Convert relative paths to absolute paths for passing to Embedded-Sharepoint build
PROJECT_C_SOURCES := $(addprefix $(MAKEFILE_DIR)/, $(PROJECT_C_SOURCES))
PROJECT_C_INCLUDES := $(addprefix $(MAKEFILE_DIR)/, $(PROJECT_C_INCLUDES))

# Debug
PRINT_DEBUG ?= true

ifeq ($(PRINT_DEBUG), true)
$(info SOURCES: $(PROJECT_C_SOURCES))
$(info INCLUDES: $(PROJECT_C_INCLUDES))
endif

# generate paths (cont.d)
PROJECT_BUILD_DIR := $(addprefix $(MAKEFILE_DIR)/, $(PROJECT_BUILD_DIR))

# export variables 
export PROJECT_TARGET
export PROJECT_C_SOURCES
export PROJECT_C_INCLUDES
export PROJECT_BUILD_DIR


# -----------------------------------------------------------------------------
# Clang
BEAR_PREFIX := 
# check if bear is installed
BEAR_INSTALLED := $(shell command -v bear >/dev/null 2>&1 && echo yes || echo no)

# define path of .vscode (create if missing)
VS_CODE_DIR := $(MAKEFILE_DIR)/.vscode
$(shell mkdir -p $(VS_CODE_DIR))

ifeq ($(BEAR_INSTALLED),yes)
BEAR_PREFIX := bear --output $(VS_CODE_DIR)/compile_commands.json --append --
endif
# -----------------------------------------------------------------------------


# BUILD -----------------------------------------------------------------------
ifeq ($(MAKECMDGOALS),)
default: build_code
else ifeq ($(MAKECMDGOALS), all)
all: build_code
else
%:
	$(BEAR_PREFIX) $(MAKE) -C $(BUILD_MAKEFILE_DIR) $(MAKECMDGOALS)
endif


build_code:
ifeq ($(MADEFILE), true)
	@echo -e "Make initiated at $(shell date)\n" > ${MADEFILE_DIR}/Madefile
endif

ifneq ($(TEST), main)
	@echo -e "Making ${PURPLE}$(PROJECT_TARGET)${NC}build for ${BLUE}TEST=${PURPLE} ${TEST}${NC}"
    ifeq ($(MADEFILE), true)
		@echo -e "Making $(PROJECT_TARGET) build for TEST=${TEST}\n" >> ${MADEFILE_DIR}/Madefile
    endif
else
	@echo -e "Making ${PURPLE}$(PROJECT_TARGET)${NC}build with ${ORANGE}main.${NC}"
    ifeq ($(MADEFILE), true)
		@echo -e "Making $(PROJECT_TARGET) build with main.\n" >> ${MADEFILE_DIR}/Madefile
    endif
endif

ifeq ($(MADEFILE), true)
	$(BEAR_PREFIX) $(MAKE) -C $(BUILD_MAKEFILE_DIR) all -j | tee -a ${MADEFILE_DIR}/Madefile
else
	$(BEAR_PREFIX) $(MAKE) -C $(BUILD_MAKEFILE_DIR) all -j
endif

	@echo -e "${GREEN}Compiled! Splendid! Jolly Good!!${NC}"
	
ifeq ($(MADEFILE), true)
	@echo -e "\nCompiled! Splendid! Jolly Good!!\n" >> ${MADEFILE_DIR}/Madefile
endif
# -----------------------------------------------------------------------------


# FLASH -----------------------------------------------------------------------
flash: 	
	$(MAKE) -C $(BUILD_MAKEFILE_DIR) flash
# -----------------------------------------------------------------------------


# FLASH -----------------------------------------------------------------------
clean:
	-rm -fR $(MADEFILE_DIR)/Madefile
	$(MAKE) -C $(BUILD_MAKEFILE_DIR) clean
# -----------------------------------------------------------------------------


# DOCUMENTATION ---------------------------------------------------------------
# .PHONY: docs
# docs:
# 	cd $(BUILD_MAKEFILE_DIR) && mkdocs serve
# -----------------------------------------------------------------------------
